# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: 지금은 개발중
subtitle: "자유로운 개발자 블로그"
email: myksb1223@gmail.com
name: Seungbeom Kim
description: >
  개발 일지, 개발 공부, 일본어 공부등을 포스팅하는 블로그입니다.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://myksb1223.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
#kramdown:
#  input: GFM
#  hard_wrap: false

#highlighter: rouge
#markdown: redcarpet
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
#  extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough"]
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: 'archive'
#  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: myksb1223

# Google analytics
ga_tracking_id: "UA-122923521-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: develop_diary
    desc: "클래스업 개발 일지 작성(Posts describing ClassUp develop stories)."

  - cat: python
    desc: "파이썬 공부 컨텐츠(Posts describing Python study contents)."

  - cat: reactnative
    desc: "리액트 네이티브 공부 컨텐츠(Posts describing React Native study contents)."

  - cat: job_review
    desc: "취업 준비에 관련된 내용"

  - cat: datastructure_algorithm
    desc: "자료구조 및 알고리즘"

  - cat: japanese_drama
    desc: "일본 드라마 소개 및 공부(Posts describing Japanese drama contents)."

  - cat: essay
    desc: "에세이(essay)"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: kim_seungbeom
    url: https://twitter.com/kim_seungbeom
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: thebencentra
    url:
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: myksb1223
    url: https://github.com/myksb1223
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Ben Centra
    url:
    desc: Connect with me on LinkedIn
    share: false

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: monseungmon
    url: https://www.instagram.com/monseungmon
    desc: Follow me on Instagram
    share: true

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: false

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
